services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - data-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    environment:
      # --- KRaft Cluster Configuration ---
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: 'localhost:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # --- Networking & Listeners ---
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:19092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      # --- Topic Constraints ---
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

      # --- Essential Internal Topic Configurations ---
      # Crucial for single-node setups to prevent default replication errors (default is 3)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # --- Storage & Logging ---
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080" # Exposes the UI on your browser at http://localhost:8080
    depends_on:
      - kafka
    networks:
      - kafka-network
    environment:
      # Name of the cluster displayed in the UI
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local-kraft-cluster'

      # Points to the internal docker network address of your Kafka broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:19092'

  posts-service:
    build: ./posts-service
    container_name: posts-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - kafka-network
      - data-network
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - ./posts-service/.env.production

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - kafka-network
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ./notification-service/.env.production

networks:
  data-network:
    driver: bridge
  kafka-network:
    driver: bridge
volumes:
  mongo_data:
  kafka_data:
