services:
  mongo:
    ports: !override []
    restart: always

  kafka:
    ports: !override []
    restart: always

  posts-service:
    ports: !override []
    restart: always

  notification-service:
    ports: !override []
    restart: always

  nginx:
    ports: !override
      - "5000:80"
    restart: always
