services:
  mongo:
    restart: always

  kafka:
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://13.223.200.168:9092

  posts-service:
    restart: always
    ports:
      - "3000:3000"

  notification-service:
    restart: always

  # optional
  kafka-ui: