events { worker_connections 1024; }

http {
    server {
        # Nginx listens inside its container on port 80
        listen 80;

        location /api {
            proxy_pass http://posts-service:3000/api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/notification/healthy {
            proxy_pass http://notification-service:4000/api/notification/healthy;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /kafka-ui {
            proxy_pass http://kafka-ui:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}